export default {
  HOME: '/',
  PORTFOLIO: '/portfolio',
  RECEIVE: '/receive',
  SEND_TX: '/send-tx',
  TX_HISTORY: '/tx-history',
  DEPLOY_CONTRACT: '/deploy-contract',
  RUN_CONTRACT: '/run-contract',
  SAVED_CONTRACTS: '/saved-contracts',
  ACTIVE_CONTRACTS: '/active-contracts',
  FAUCET: '/faucet',
  LOADING: '/loading',
  UNLOCK_WALLET: '/unlock-wallet',
  BLOCKCHAIN_LOGS: '/blockchain-logs',
  CGP: '/cgp',
  ALLOCATION: '/allocation',
  SETTINGS: '/settings',
  // Onboarding routes
  WELCOME_MESSAGES: '/welcome-messages',
  IMPORT_OR_CREATE_WALLET: '/import-or-create-wallet',
  IMPORT_WALLET: '/import-wallet',
  SECRET_PHRASE: '/secret-phrase',
  SECRET_PHRASE_QUIZ: '/secret-phrase-quiz',
  SET_PASSWORD: '/set-password',
  TERMS_OF_SERVICE: '/terms-of-service',
  ERROR_REPORTING_OPT_IN: '/error-reporting-opt-in',
}
